name: aws-ebs-volume-tagger
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/aws-ebs-volume-tagger
  tag: v0.0.1
  pullPolicy: IfNotPresent

schedule: "*/15 * * * *"
